# Generated by Django 5.2.7 on 2025-10-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
