# Generated by Django 5.2.7 on 2025-11-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_matchrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
